LIBS = #-lm
CC = gcc
CFLAGS = #-g -Wall




all:
		$(CC) client.c -o client
		$(CC) server.c -o server




# clean:
# 	-rm -f $(BUILD_DIR)$(TARGET)
# 	-rm -f $(BUILD_DIR)*.o

# run:
# 	$(BUILD_DIR)binary