TARGET1 = binary_1
TARGET2 = binary_2
LIBS = #-lm
CC = gcc
CFLAGS = #-g -Wall

SRC_DIR = ./
BUILD_DIR = ../build/




all:
		$(CC) main_1.c -o main_1
		$(CC) main_2.c -o main_2







# clean:
# 	-rm -f $(BUILD_DIR)$(TARGET)
# 	-rm -f $(BUILD_DIR)*.o

# run:
# 	$(BUILD_DIR)binary